baseURL: "https://joshuathorp.github.io"
title: Joshua R. Thorp
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Dissertation
          url: /dissertation/
          weight: 1
        - name: Research
          url: /research/
          weight: 2 
        - name: Teaching
          url: /teaching/
          weight: 3
        - name: CV
          url: /cv/
          weight: 4

params:
    description: "PhD Candidate in political science at the University of Michigan"
    author: Joshua R. Thorp
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","dissertation","teaching","CV"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: <span style="color:#011F5B">Joshua R. Thorp</span>
          subtitle: I am a PhD candidate in political science at the University of Michigan, specializing in ​public opinion, political psychology, and public policy. <span style="color:#011F5B"> I am on the political science job market in 2024-25 </span>. My dissertation project uses original surveys and experiments to examine the role of disability in shaping the identities of Americans with disabilities. More information about my doctoral research, including my job market paper, is available at my dissertation page.<br><br> 
          
          In addition to my doctoral research, I have several ongoing projects examining public attitudes toward redistributive and social policy in advanced democracies. My research has been published at venues including *Political Psychology* and the *Journal of Experimental Political Science*. 
          imageUrl: "IMG_0219.HEIC"
          imageWidth: 200
          imageHeight: 200
          imageTitle: JT
          buttons:
            - name: Dissertation
              url: /dissertation/
            - name: Research
              url: /research/
            - name: Teaching
              url: /teaching/
            - name: CV
              url: /JTCV_Aug2024.pdf
            - name: Job-Market Paper
              url: jmp.pdf

    socialIcons:
        - name: CV
          url: /JTCV_August2024.pdf
        - name: Email
          url: mailto:jrthorp@umich.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=XvlxqvkAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/joshuathorp
        - name: X
          url: https://X.com/JoshuaThorp
        - name: bluesky
          url: https://bsky.app/profile/joshuathorp.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Joshua R. Thorp"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
