baseURL: "https://joshthorp.com"
title: Joshua R. Thorp
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Book Project
          url: /bodypolitic/
          weight: 1
        - name: Research
          url: /research/
          weight: 2 
        - name: Teaching
          url: /teaching/
          weight: 3
        - name: CV
          url: /cv/
          weight: 4

params:
    description: "PhD Candidate in Political Science (American Politics) at the University of Michigan"
    author: Joshua R. Thorp
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","dissertation","teaching","CV"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: <span style="color:#011F5B">Joshua R. Thorp</span>
          subtitle: 
              I am an incoming Assistant Professor of Public Opinion (Fall 2025) at the University of Arkansas, Fayetteville. My research focuses on public opinion and political psychology in the United States and other advanced democracies. My dissertation and book project explores the role of political processes - such as policy feedback, experiences of stigma and discrimination, and exposure to protest action - in the shaping the political identities of people with disabilities. <br><br>
              I received my Ph.D. from the University of Michigan in 2025. My research has been published in peer-reviewed journals including <em>Political Psychology</em> and the <em>Journal of Experimental Political Science</em>, and is generously supported by the British Academy/Leverhulme Trust, the Center for Political Studies at the University of Michigan, the Rapoport Family Foundation, and Time-Sharing Experiments in the Social Sciences (TESS).
          imageUrl: "jiaWOLZR_400x400.jpg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: JT
          buttons:
            - name: Book Project
              url: /bodypolitic/
            - name: Research
              url: /research/
            - name: Teaching
              url: /teaching/
            - name: CV
              url: https://www.dropbox.com/scl/fi/n72gapbvxx04uooczhnou/JTCV_Aug2025.pdf?rlkey=72ya9zdkuqexfmldfg81tq4jk&st=p3y79zwr&dl=0

    socialIcons:
        - name: CV
          url: https://www.dropbox.com/scl/fi/n72gapbvxx04uooczhnou/JTCV_Aug2025.pdf?rlkey=72ya9zdkuqexfmldfg81tq4jk&st=p3y79zwr&dl=0
        - name: Email
          url: /mailto:jrthorp@umich.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=XvlxqvkAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/joshuathorp
        - name: X
          url: https://X.com/JoshuaThorp
        - name: bluesky
          url: https://bsky.app/profile/joshuathorp.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Joshua R. Thorp"
      icon: /michigan.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
