baseURL: "https://joshuathorp.github.io"
title: Joshua R. Thorp
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 5 
        - name: Teaching
          url: teaching/
          weight: 2
        - name: CV
          url: cv/
          weight: 3

params:
    description: "I am a PhD candidate in political science at the University of Michigan. I study public opinion and political psychology in the United States and other advanced democracies."
    author: Joshua R. Thorp
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","dissertation","teaching","CV"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joshua R. Thorp
          subtitle: "I am a PhD candidate in political science at the University of Michigan, specializing in ​political behavior and political psychology"
          imageUrl: "JT_MCARD.jpeg"
          imageWidth: 170
          imageHeight: 180
          imageTitle: JT
          buttons:
            - name: Research
              url: research/
            - name: Dissertation
              url: dissertation/
            - name: Teaching
              url: teaching/
            - name: CV
              url: cv/
    socialIcons:
        - name: CV
          url: JTCV_August2024.pdf
        - name: Email
          url: mailto:jrthorp@umich.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=XvlxqvkAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/joshuathorp
        - name: X
          url: https://X.com/JoshuaThorp

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Joshua Rutherford Thorp"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
