baseURL: "https://joshuathorp.github.io"
title: Joshua R. Thorp
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Dissertation
          url: /dissertation/
          weight: 1
        - name: Research
          url: /research/
          weight: 2 
        - name: Teaching
          url: /teaching/
          weight: 3
        - name: CV
          url: /cv/
          weight: 4

params:
    description: "PhD Candidate in Political Science (American Politics) at the University of Michigan"
    author: Joshua R. Thorp
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","dissertation","teaching","CV"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: <span style="color:#011F5B">Joshua R. Thorp</span>
          subtitle: 
              Welcome! I am a PhD candidate in political science (American politics) at the University of Michigan, specializing in public opinion, political psychology, and public policy. My dissertation project draws on data from original national surveys and experiments to examine the role of political processes - such as policy feedback, experiences of stigma and discrimination, and exposure to protest action - in shaping the political identities of Americans with disabilities.<br><br> 
              
              In addition to my doctoral research, I have several ongoing projects in political psychology and public policy in the United States and other advanced democracies. I am particularly interested in how intergroup prejudice and stereotypes shape attitudes toward social policy. My research has been published in peer-reviewed journals including *Political Psychology* and the *Journal of Experimental Political Science*.<br><br>  
              
              At Michigan, I am affiliated with the Center for Political Studies at the Institute for Social ​Research (ISR). My research is funded by the British Academy/Leverhulme Trust, the Rapoport Family Foundation, the Center for Political Studies at the University of Michigan, and Time-Sharing Experiments in the Social Sciences (TESS). <span style="color:#011F5B">**I am on the job market in 2024-25**</span>.
          imageUrl: "jiaWOLZR_400x400.jpg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: JT
          buttons:
            - name: Dissertation
              url: /dissertation/
            - name: Research
              url: /research/
            - name: Teaching
              url: /teaching/
            - name: CV
              url: https://www.dropbox.com/scl/fi/b7c4zsxu82f3jgdqrrwwe/JTCV_Nov24.pdf?rlkey=fobryk08j9h1jxgpz3vkzzxyo&st=uwvpsp5q&dl=0
            - name: Job-Market Paper
              url: /JMP_Oct2024.pdf

    socialIcons:
        - name: CV
          url: https://www.dropbox.com/scl/fi/b7c4zsxu82f3jgdqrrwwe/JTCV_Nov24.pdf?rlkey=fobryk08j9h1jxgpz3vkzzxyo&st=uwvpsp5q&dl=0
        - name: Email
          url: /mailto:jrthorp@umich.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=XvlxqvkAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/joshuathorp
        - name: X
          url: https://X.com/JoshuaThorp
        - name: bluesky
          url: https://bsky.app/profile/joshuathorp.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Joshua R. Thorp"
      icon: /michigan.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
